<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>超市收银</title>
		<style type="text/css">
			table{
				border-collapse: collapse;
				font-family: "微软雅黑";
				text-align: center;
			}
			td{
				width: 100px;height: 40px;
				border: 1px solid black;
			}
		</style>
		<script type="text/javascript">
			var zg=0;
			function add(btn){
				var tb2=document.getElementById("tb2");
				var tbw1=btn.parentNode.parentNode.children;				
			    var	tw=tbw1[0].innerText;
				var td=tbw1[1].innerText;
				bug(tw);				
				var tr2=document.createElement("tr");
				tr2.innerHTML='<td>'+tw+'</td>'+'<td>'+td+'</td>'+
				'<td>'+'<button onclick=ad(this)>'+'+'+'</button>'+
				    '<button>'+'1'+'</button>'+
				'<button onclick="ja(this)">'+'-'+'</button>'+'</td>';
				 tb2.appendChild(tr2);
				 clear(tr2);
			}
			function ad(btn){
				var but=btn.parentNode.children;
				var li=but[1].innerText;
				li++;
				but[1].innerText=li;
			}
			function ja(btn){
				var but=btn.parentNode.children;
				var li=but[1].innerText;
				li--;
				if(li==0){
					var c=btn.parentNode.parentNode;
					var tb2=document.getElementById("tb2");
					tb2.removeChild(c);
				}
				but[1].innerText=li;								
			}	
			function wei(){
				var tai=document.getElementById("tai");
				var ku=0;
				while(tai.innerText!="支付完成"){
			    var user=eval(prompt("已支付:"+ku+","+"请支付金额："));
			    ku=user+ku;
				if(ku>=zg){
					var shou=document.getElementById("shou");
					shou.innerText=ku;
					var ling=document.getElementById("ling");
					ku=ku-zg;
					ling.innerText=ku;
					var tai=document.getElementById("tai");
					tai.innerText="支付完成";
				    }
				}		
			}
			function bug(tw){
			   var tb2=document.getElementById("tb2");
			   var trs=tb2.children;
			   for(var i=0;i<trs.length;i++){
			   	var tds=trs[i].children;
			   	 if(tw==tds[0].innerText){
			   	 	var btn=tds[2].children;
			   	 	var v=btn[1].innerText;
			   	 	v++;
			   	 	btn[1].innerText=v;
			   	 }
			   }
			}
			function clear(tr2){
			   var tb2=document.getElementById("tb2");
			   var trs=tb2.children;
			   var s=0;
			      for(var i=0;i<trs.length;i++){			      
			      	  var trr=tr2.children;
			      	  var ttr=trs[i].children;			      
			      	  var bm=ttr[0].innerText;
			      	  var bn=trr[0].innerText;
			      	  if(bm==bn){			      	  	 
			      	  	s++;
			      	  	if(s>1){
			      	  		tb2.removeChild(tr2);
			      	  	}
			      	 }
			     }
			}
			function end(){
				var tb2=document.getElementById("tb2");
				var trs=tb2.children;
				for(var i=0;i<trs.length;i++){
					var td=trs[i].children;
					var d=td[1].innerText;
					var btn=td[2].children;
					var s=btn[1].innerText;
					zg=zg+(d*1)*(s*1);				
				}			
					var money=document.getElementById("money");
					money.innerText=zg;
					setTimeout(function(){
						wei();
					},1000);
			}
		</script>
	</head>	
	<body>
		<div id="box" style="width: 300px;height: 100%;margin: 0 auto;">
			<div>
			<table>
				<thead>
					<tr>
						<td>物品</td>
						<td>单价（元）</td>
						<td>购物</td>
					</tr>
				</thead>
				<tr>
					<td>1号</td>
					<td>10</td>
					<td><button onclick="add(this)">+</button></td>
				</tr>
				<tr>
					<td>2号</td>
					<td>20</td>
					<td><button onclick="add(this)">+</button></td>
				</tr>
				<tr>
					<td>3号</td>
					<td>30</td>
					<td><button onclick="add(this)">+</button></td>
				</tr>
				<tr>
					<td>4号</td>
					<td>40</td>
					<td><button onclick="add(this)">+</button></td>
				</tr>
			</table>
		</div><br />
		<div>
			<table>
				<thead>
				  <tr>
					<td>物品</td>
					<td>单价（元）</td>
					<td>数量</td>
				  </tr>
				</thead>
				<tbody id="tb2">					
				</tbody>
				<tfoot>
					<tr>
						<td onclick="end()" style="background-color:red ;">结算金额</td>
						<td colspan="2" id="money"></td>
					</tr>
				</tfoot>
			</table>
		</div><br />
		<div>
			<table>
				<thead>
					<tr>
						<td>用户支入金额</td>
						<td>找零</td>
						<td>交易状态</td>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td id="shou"></td>
						<td id="ling"></td>
						<td id="tai">支付未完成</td>
					</tr>
				</tbody>
			</table>
		</div>
		</div>		
	</body>
</html>
